### ISSUE TITLE
Can't decode images

### ISSUE THREAD

**Issue by KylePiira** [erwinmatijsen/django-markdownify#1]
`![By NASA (NASA) Public domain, via Wikimedia Commons](https://upload.wikimedia.org/wikipedia/commons/8/8c/Mosaic_of_the_Arctic.jpg "Earth") `
Does not get converted properly to 
`<img src="https://upload.wikimedia.org/wikipedia/commons/8/8c/Mosaic_of_the_Arctic.jpg" title="Earth">`

**Comment by erwinmatijsen** [comment]
That's because django-markdownify uses [bleach](https://bleach.readthedocs.io/en/latest/index.html) which by default strips the <code>src</code> attribute.

To fix this, edit <code>templatetags/markdownify.py</code> to look something like this:

```Python
@register.filter
def markdownify(text):
    # safe mode is deprecated, see: https://pythonhosted.org/Markdown/reference.html#safe_mode
    untrusted_text = markdown.markdown(text, safe_mode='escape')
    html = bleach.clean(untrusted_text,
                        tags=settings.MARKDOWNIFY_WHITELIST_TAGS,
			attributes=settings.MARKDOWNIFY_WHITELIST_ATTRS, ) # Add this line
    html = bleach.linkify(html)
    return html
```

And then in your settings.py add:

```Python
MARKDOWNIFY_WHITELIST_ATTRS = [
    'src',
]
```
(and other attributes you want to allow)
