### ISSUE TITLE
setup.py failes trying to read "README.rst"

### ISSUE THREAD

**Issue by julidau** [erwinmatijsen/django-markdownify#16]
Hi, 
maybe i am overlooking something simple, but i tried to build this package using 
```
python setup.py build
```

which resulted in it failing with 

```
README = open(os.path.join(os.path.dirname(__file__), 'README.rst')).read()
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst
```

And indeed the file is missing. Could you maybe explain why you changed that line in bb6b7b60 ? Sorry in advance if this is a stupid or obvious thing..

**Comment by erwinmatijsen** [comment]
In the setup.py file it points to README.rst, but that doesn't exists. README.md does, however. Simple mistake I guess, I fixed the setup.py and will push the fix to pypi soon.

NB: I never noticed it because I don't use `python setup.py build`, but do a pip install in a project, and than it doesn't complain about the missing readme.
