### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by erwinmatijsen** [erwinmatijsen/django-markdownify#3]
@RRMoelker Are you interested in maintaining this package? I (and @alexhayes) made some small additions and improvements which could benefit others as well. 

I don't really want to push a fork to PyPi, so I would be glad to take over maintenance of your package.

**Comment by RRMoelker** [comment]
Hey, I'm on holiday right now. I'll look into it later this week.


On Jul 31, 2017 23:28, "Erwin Matijsen" <notifications@github.com> wrote:

@RRMoelker <https://github.com/rrmoelker> Are you interested in maintaining
this package? I (and @alexhayes <https://github.com/alexhayes>) made some
small additions and improvements which could benefit others as well.

I don't really want to push a fork to PyPi, so I would be glad to take over
maintenance of your package.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RRMoelker/django-markdownify/issues/3>, or mute the
thread

**Comment by erwinmatijsen** [comment]
Ok, thanks. I made a PR, so you can see the differences.

**Comment by RRMoelker** [comment]
Nice PR. I'm no longer using Django, so I'm happy to hand over maintenance. Can you message me your Pypi account? I'll try to pass package control over to you, @erwinmatijsen.

As for the GitHub repo. I'm not sure what the best approach is. Either I redirect people to your fork or I add you as collaborator. I'm guessing my repo will be the first hit in Google. So shall I simply add you as admin?

**Comment by erwinmatijsen** [comment]
Thanks. I'm evosites on Pypi. I think me collaborating on this repo would be best.

**Comment by RRMoelker** [comment]
Alright, you should have access. If you need anything else please ask.

Bedankt en succes ;)

**Comment by erwinmatijsen** [comment]
Haha, bedankt!

**Comment by erwinmatijsen** [comment]
@RRMoelker Can you please transfer the repository to my account? I'm currently maintaining this actively, and need to set up integration with Read the docs. After a transfer you will be set as collaborator and all commits, merges, pull requests, issues, etc will be kept intact. See https://help.github.com/articles/about-repository-transfers/

**Comment by RRMoelker** [comment]
Ok, transfer request send out. Take good care of it :)

**Comment by erwinmatijsen** [comment]
Thanks, I will!
